name: run playwright tests
on:
  # push:
  #   branches: [ main ]
  # pull_request:
  workflow_dispatch:
jobs:
  test:
    environment: ${{ matrix.environment }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: rionet
          - environment: seoulnet
          - environment: ghostnet
    env:
      VITE_NETWORK_TYPE: ${{ matrix.environment }}
      VITE_RPC_URL: ${{ vars.RPC_URL }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Originate Counter Contract
      run: npm run originate ${{ secrets.WALLET_PRIVATE_KEY }}
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test staking.spec.ts
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-artifacts
        path: |
          playwright-report/
          test-results/
          test-results/**/*.zip
          test-results/**/*.webm
        retention-days: 15
